name: Ping Render App

on:
  schedule:
    - cron: "*/1 * * * *"   # chạy mỗi 1 phút
  workflow_dispatch:         # cho phép chạy thủ công nếu muốn

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render endpoint
        run: |
          echo "Pinging Render app..."
          curl -s -o /dev/null -w "%{http_code}\n" https://podcast-shoppings.onrender.com/cron-check
