name: Ping Render App

on:
  schedule:
    - cron: "*/5 * * * *"  # chạy mỗi 5 phút
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render app
        run: |
          curl -s -L https://podcast-shoppings.onrender.com > /dev/null

      - name: Wait for Render to wake up
        run: |
          sleep 20  # chờ 20 giây để app khởi động lại hoàn toàn

      - name: Trigger email job
        run: |
          curl -s -L https://healink-ewaybqg9encadbe8.southeastasia-01.azurewebsites.net/api/emails/run-email-job > /dev/null
