name: Ping Render App

on:
  schedule:
    - cron: "*/5 * * * *"  # chạy mỗi 5 phút
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -s https://your-render-app-name.onrender.com > /dev/null
