name: Ping Render & Azure Email Job

on:
  schedule:
    - cron: "*/5 * * * *"  # chạy mỗi 5 phút
  workflow_dispatch:         # có thể chạy thủ công nếu muốn

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up Render app
        run: |
          echo "🟡 Waking up Render app..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://podcast-shoppings.onrender.com)
          if [ "$response" -eq 200 ]; then
            echo "✅ Render app responded successfully!"
          else
            echo "⚠️ Render app may still be sleeping (HTTP $response)"
          fi

      - name: Wait for Render to wake up
        run: |
          echo "⏳ Waiting for Render app to stabilize..."
          sleep 20

      - name: Trigger Azure email job
        run: |
          echo "📧 Triggering scheduled email job on Azure..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://healink-ewaybqg9encadbe8.southeastasia-01.azurewebsites.net/api/emails/run-email-job)
          if [ "$response" -eq 200 ]; then
            echo "✅ Azure email job triggered successfully!"
          else
            echo "❌ Azure email job failed with HTTP code: $response"
          fi

      - name: Log timestamp
        run: |
          echo "🕒 Job completed at $(date '+%Y-%m-%d %H:%M:%S')"
